# Generated by Django 4.2 on 2023-05-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_categoria_options_juego'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('nombre',)},
        ),
        migrations.AlterModelOptions(
            name='juego',
            options={'ordering': ('nombre',)},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nombre',
        ),
    ]
